<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-PackCall.Worker-aac2b32d-f8a4-453f-b9dd-d23400af8d9f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PackCall.Core\PackCall.Core.csproj" />
    <ProjectReference Include="..\PackCall.Infrastructure\PackCall.Infrastructure.csproj" />
  </ItemGroup>
</Project>
